import {
  buildScenario,
  type RawEvent,
  type Scenario,
} from '../types';

/** 初始光标：停在 v2 修复后、v3 复测前（仪表盘显示“运行中 · 测试 4/7”） */
export const RESNET_INITIAL_CURSOR_MIN = 31;

const raw: RawEvent[] = [
  // ── 阶段 1：识别 ────────────────────────────────────────────
  { tsMin: 0, stage: 'identify', kind: 'stage_started', title: '开始算子识别' },
  {
    tsMin: 0.05,
    stage: 'identify',
    kind: 'session_started',
    sessionId: 's1-identify',
    title: 'identify 会话 · 图解析与热点画像',
    detail: '识别',
  },
  {
    tsMin: 0.2,
    stage: 'identify',
    kind: 'session_message',
    sessionId: 's1-identify',
    title: '思考',
    message: {
      part: 'thinking',
      content:
        '先解析 ONNX 图结构与静态 shape，再做算子分布画像——重点看 Conv2D 计算占比和 BN/ReLU 这类逐元素算子的配对关系，它们决定融合收益的上限。',
    },
  },
  {
    tsMin: 0.3,
    stage: 'identify',
    kind: 'tool_completed',
    sessionId: 's1-identify',
    title: '解析模型文件',
    tool: {
      name: 'parse_model',
      input: { file: 'resnet50_bs16.onnx', format: 'ONNX' },
      output: { ops: 42, graph_nodes: 176, input_shape: 'NCHW 16×3×224×224' },
      durationMs: 4_200,
    },
  },
  {
    tsMin: 1.2,
    stage: 'identify',
    kind: 'tool_completed',
    sessionId: 's1-identify',
    title: '算子分布画像',
    tool: {
      name: 'op_profile',
      output: {
        top: ['Conv2D ×53', 'BatchNorm ×53', 'ReLU ×53', 'GEMM ×1', 'Pooling ×8'],
        macs: '4.1 GFLOPs / img',
      },
    },
  },
  {
    tsMin: 3,
    stage: 'identify',
    kind: 'decision',
    title: 'Conv2D 计算占比 63%，BN/ReLU 为逐元素算子，融合价值高',
    severity: 'info',
  },
  {
    tsMin: 5,
    stage: 'identify',
    kind: 'tool_completed',
    sessionId: 's1-identify',
    title: '扫描融合机会',
    tool: {
      name: 'fusion_scan',
      input: { min_fusion_gain: 0.03 },
      output: {
        candidates: 6,
        top: [
          { pattern: 'Conv2D+BN+ReLU', count: 16, est_gain: '+8~10%' },
          { pattern: 'Conv1x1 纵向融合', count: 12, est_gain: '+4%' },
          { pattern: 'GEMM+Add+ReLU', count: 1, est_gain: '+3%' },
        ],
      },
    },
  },
  {
    tsMin: 8,
    stage: 'identify',
    kind: 'tool_completed',
    sessionId: 's1-identify',
    title: '检索知识库确认融合模式',
    tool: {
      name: 'retrieve',
      input: { query: 'Conv2D BatchNorm ReLU 融合 推理折叠', top_k: 3 },
      output: {
        hits: [
          { source: '经验库 #exp-0117', title: 'BN 推理态折叠为 scale/shift', score: 0.91 },
          { source: 'CANN 文档', title: 'AscendC 算子开发指南 · 向量算子', score: 0.86 },
          { source: '经验库 #exp-0089', title: 'ReLU epilogue 融合至 Mmad 出口', score: 0.83 },
        ],
      },
    },
  },
  {
    tsMin: 8.8,
    stage: 'identify',
    kind: 'session_ended',
    sessionId: 's1-identify',
    title: 'identify 完成',
  },
  {
    tsMin: 9,
    stage: 'identify',
    kind: 'stage_completed',
    title: '识别完成：42 个算子 / 6 类融合机会',
    severity: 'success',
  },

  // ── 阶段 2：策略 ────────────────────────────────────────────
  { tsMin: 9.1, stage: 'strategy', kind: 'stage_started', title: '开始策略生成' },
  {
    tsMin: 9.15,
    stage: 'strategy',
    kind: 'session_started',
    sessionId: 's2-strategy',
    title: 'strategy 会话 · 方案生成',
    detail: '策略',
  },
  {
    tsMin: 9.3,
    stage: 'strategy',
    kind: 'session_message',
    sessionId: 's2-strategy',
    title: '思考',
    message: {
      part: 'thinking',
      content:
        '候选排序：Conv2D+BN+ReLU 融合（16 处、+8~10%）收益最高且模式最成熟——BN 推理态折叠消两次访存，ReLU 进 epilogue。GEMM+Add 只有 1 处，优先级放后。先检索 AscendC 实现先例确认 epilogue 写法。',
    },
  },
  {
    tsMin: 9.5,
    stage: 'strategy',
    kind: 'tool_completed',
    sessionId: 's2-strategy',
    title: 'RAG 检索融合先例',
    tool: {
      name: 'retrieve',
      input: { query: 'Conv2D+BN+ReLU AscendC 融合实现', top_k: 3 },
      output: {
        hits: [
          { source: '经验库 #exp-0117', title: 'BN 推理态折叠：w←w·γ/σ，b←β−μγ/σ', score: 0.91 },
          { source: 'CANN 文档', title: 'Mmad 接口与 epilogue 修饰', score: 0.88 },
          { source: '经验库 #exp-0063', title: 'NC1HWC0 布局转换时机', score: 0.80 },
        ],
      },
    },
  },
  {
    tsMin: 11,
    stage: 'strategy',
    kind: 'decision',
    title: '选定首批优化对象：Conv2D+BN+ReLU 融合（16 处，覆盖全部热点段）',
    severity: 'info',
  },
  {
    tsMin: 13,
    stage: 'strategy',
    kind: 'tool_completed',
    sessionId: 's2-strategy',
    title: '生成融合方案 #2',
    tool: {
      name: 'strategy_gen',
      input: { pattern: 'Conv2D+BN+ReLU', impl: 'AscendC 混合算子' },
      output: {
        plan: '方案#2',
        est_gain: '+8%',
        risk: 'fp16 累积精度需验证',
      },
      durationMs: 96_000,
    },
    artifact: {
      tab: 'strategy',
      title: '优化策略文档 · 方案#2',
      data: {
        content: [
          '# Conv2D + BN + ReLU 融合优化策略（方案#2）',
          '',
          '## 目标',
          '- 输入模型：resnet50（bs16，224×224），16 处 Conv2D+BN+ReLU 热点段',
          '- 目标：单段时延相对官方实现提升 ≥ +5%',
          '',
          '## 融合方案',
          '- BN 推理态折叠：权重与偏置预计算合入 GEMM（w ← w·γ/σ，b ← β − μγ/σ），消除两次逐元素访存',
          '- ReLU epilogue：激活函数融合至 Mmad 出口寄存器操作，不再落盘 UB',
          '- 数据布局：NCHW → NC1HWC0 对齐转换前移至 host 侧一次完成',
          '- Tiling：按 Cube 基本块（M16N16K16）整除切分，tiling 参数随 shape 静态生成',
          '',
          '## 预期收益',
          '- 消除 BN/ReLU 两次 GM→UB 搬运与 kernel 启动开销，预计 +8%',
          '',
          '## 风险与对策',
          '- fp16 累积精度：累加器与中间态升 fp32（见经验库 #exp-0117）',
          '- padding 边界：掩码读取，避免越界脏数据',
        ].join('\n'),
      },
    },
  },
  {
    tsMin: 15,
    stage: 'strategy',
    kind: 'checkpoint',
    title: '检查点：策略定稿',
    detail: '墙钟余量 75min / 90min · 策略会话 token 累计 38k / 1M（余量充足）',
  },
  {
    tsMin: 18.8,
    stage: 'strategy',
    kind: 'session_message',
    sessionId: 's2-strategy',
    title: '输出',
    message: {
      part: 'text',
      content:
        '方案#2 定稿：BN 折叠 + ReLU epilogue + NC1HWC0 布局前移，预期 +8%，主要风险是 fp16 累积精度（对策：中间态升 fp32）。转入编码。',
    },
  },
  {
    tsMin: 18.9,
    stage: 'strategy',
    kind: 'session_ended',
    sessionId: 's2-strategy',
    title: 'strategy 完成',
  },
  {
    tsMin: 19,
    stage: 'strategy',
    kind: 'stage_completed',
    title: '策略完成：方案#2 · 预期 +8%',
    severity: 'success',
  },

  // ── 阶段 3：编码 ────────────────────────────────────────────
  { tsMin: 19.1, stage: 'implement', kind: 'stage_started', title: '开始代码编写' },
  {
    tsMin: 19.15,
    stage: 'implement',
    kind: 'session_started',
    sessionId: 's3-impl-v1',
    title: 'implement 会话 · v1',
    detail: '编码',
  },
  {
    tsMin: 19.25,
    stage: 'implement',
    kind: 'session_message',
    sessionId: 's3-impl-v1',
    title: '思考',
    message: {
      part: 'thinking',
      content:
        '骨架：host 侧下发折叠后的 w_fused/b_fused（TilingData 携带）→ kernel 内 GEMM 主循环按 M16N16K16 基本块切分 → ReLU 在 Mmad 出口寄存器直接做，不落 UB。布局转换前移到 host。',
    },
  },
  {
    tsMin: 19.4,
    stage: 'implement',
    kind: 'tool_completed',
    sessionId: 's3-impl-v1',
    title: '生成融合算子 v1 代码',
    tool: {
      name: 'code_gen',
      input: { file: 'operator/conv_bn_relu_v1.cpp', lines: 214 },
      output: { status: 'generated', warnings: 0 },
      durationMs: 210_000,
    },
    artifact: {
      tab: 'diff',
      title: '融合算子 v1 生成',
      data: {
        file: 'operator/conv_bn_relu_v1.cpp（新增 214 行）',
        summary: 'AscendC 混合算子骨架：BN 折叠权重加载 + GEMM + ReLU epilogue',
        diff: [
          '@@ operator/conv_bn_relu_v1.cpp @@',
          '+ extern "C" __global__ __aicore__ void conv_bn_relu(GM_ADDR x, GM_ADDR w,',
          '+     GM_ADDR b, GM_ADDR y, GM_ADDR workspace, GM_ADDR tiling) {',
          '+   ConvBnReluKernel<pipeline::ALL>() op;',
          '+   op.Init(x, w, b, y, workspace, tiling, GetBlockIdx());',
          '+   op.Process();',
          '+ }',
          '+',
          '+ // BN 折叠：w_fused = w * gamma / sqrt(var + eps)',
          '+ //         b_fused = beta - mu * gamma / sqrt(var + eps)',
          '+ __aicore__ inline void FoldBn(const LocalTensor<half>& w, ...)',
          '+   // w_fused 与 b_fused 由 host 侧 TilingData 随任务下发',
        ].join('\n'),
      },
    },
  },
  {
    tsMin: 21,
    stage: 'implement',
    kind: 'tool_failed',
    sessionId: 's3-impl-v1',
    title: '编译失败：tiling 参数越界',
    severity: 'error',
    detail: 'E104: tiling_N=128 超出 N=64 时 UB 容量约束',
    tool: {
      name: 'build',
      input: { target: 'ascend910b', mode: 'release' },
      output: { error: 'E104 TILING: tiling_N=128 exceeds UB limit for N=64' },
      durationMs: 38_000,
    },
  },
  {
    tsMin: 21.3,
    stage: 'implement',
    kind: 'session_message',
    sessionId: 's3-impl-v1',
    title: '思考',
    message: {
      part: 'thinking',
      content:
        'E104：GetTilingData 没按 BLOCK 对齐——N=64 时 tiling_N=128 超出 UB。改成对齐取整（ceil 到 BLOCK）并加 UB 上限校验，两行的事。',
    },
  },
  {
    tsMin: 21.5,
    stage: 'implement',
    kind: 'tool_completed',
    sessionId: 's3-impl-v1',
    title: '定位编译错误',
    tool: {
      name: 'analyze_error',
      input: { log: 'build_v1.log' },
      output: {
        root_cause: 'GetTilingData 未按 BLOCK 对齐约束计算 tiling_N',
        fix: 'tiling_N = ceil(N / BLOCK) * BLOCK，且校验 UB 占用',
      },
    },
  },
  {
    tsMin: 22.2,
    stage: 'implement',
    kind: 'tool_completed',
    sessionId: 's3-impl-v1',
    title: '修复 tiling 计算',
    tool: { name: 'patch_code', input: { file: 'tiling.h', lines_changed: 2 } },
    artifact: {
      tab: 'diff',
      title: '修复 tiling 越界',
      data: {
        file: 'operator/tiling.h',
        summary: 'tiling_N 按 BLOCK 对齐并校验 UB 容量',
        diff: [
          '@@ operator/tiling.h @@',
          '  uint32_t CalcTilingN(uint32_t n) {',
          '-   return n > 128 ? 128 : n;',
          '+   const uint32_t aligned = CeilDiv(n, BLOCK) * BLOCK;',
          '+   return aligned > MAX_UB_N ? MAX_UB_N : aligned;',
          '  }',
        ].join('\n'),
      },
    },
  },
  {
    tsMin: 23.5,
    stage: 'implement',
    kind: 'tool_completed',
    sessionId: 's3-impl-v1',
    title: '重新编译通过',
    severity: 'success',
    tool: {
      name: 'build',
      output: { binary: 'conv_bn_relu_v1.o', warnings: 1 },
      durationMs: 42_000,
    },
  },
  {
    tsMin: 26,
    stage: 'implement',
    kind: 'note',
    title: 'v1 编译通过，进入精度验证',
  },
  {
    tsMin: 26.8,
    stage: 'implement',
    kind: 'session_ended',
    sessionId: 's3-impl-v1',
    title: 'implement·v1 完成（build 通过）',
  },
  {
    tsMin: 27,
    stage: 'implement',
    kind: 'stage_completed',
    title: '编码完成：v1 编译通过',
    severity: 'success',
  },

  // ── 阶段 4：测试（迭代 v1→v3）─────────────────────────────
  { tsMin: 27.1, stage: 'verify', kind: 'stage_started', title: '开始测试回归' },
  {
    tsMin: 27.15,
    stage: 'verify',
    kind: 'session_started',
    sessionId: 's4-verify',
    title: 'verify 会话 · v1 精度验证',
    detail: '测试',
  },
  {
    tsMin: 27.2,
    stage: 'verify',
    kind: 'session_message',
    sessionId: 's4-verify',
    title: '思考',
    message: {
      part: 'thinking',
      content:
        '用例设计：random ×64 覆盖常规分布 + boundary ×16 打边界（固定 seed 保证可复现）。基线用官方单算子 API 逐个调用并关闭 ATC 自动融合——否则对比口径会被图优化污染。',
    },
  },
  { tsMin: 27.3, stage: 'verify', kind: 'iteration_started', title: '迭代 v1：精度验证', iteration: 'v1' },
  {
    tsMin: 27.5,
    stage: 'verify',
    kind: 'tool_completed',
    sessionId: 's4-verify',
    title: '生成测试用例',
    detail: '基线：官方 Conv2D / BN / ReLU 单算子 API 逐个调用（关闭 ATC 自动融合，排除干扰）',
    tool: {
      name: 'gen_test',
      input: { cases: 'random ×64 + boundary ×16', atc: '--disable_fusion' },
      output: { cases: 80, seed: 20260915 },
    },
  },
  {
    tsMin: 29,
    stage: 'verify',
    kind: 'tool_failed',
    sessionId: 's4-verify',
    title: 'v1 精度超差',
    severity: 'error',
    detail: 'max_rel_err 3.1e-2，阈值 1e-3，失败 9 / 80 例',
    tool: {
      name: 'run_test',
      output: { max_rel_err: 3.1e-2, threshold: 1e-3, fail_cases: '9/80' },
      durationMs: 64_000,
    },
  },
  {
    tsMin: 29.6,
    stage: 'verify',
    kind: 'tool_completed',
    sessionId: 's4-verify',
    title: '精度归因分析',
    tool: {
      name: 'analyze_accuracy',
      output: {
        root_cause: 'fp16 中间累积误差：BN scale 后求和在 fp16 下溢出精度',
        loc: 'Compute() 内累加器',
        ref: '经验库 #exp-0117 建议中间态升 fp32',
      },
    },
  },
  {
    tsMin: 29.75,
    stage: 'verify',
    kind: 'session_ended',
    sessionId: 's4-verify',
    title: 'v1 验证收尾：未达标，进入分叉点',
  },
  {
    tsMin: 29.8,
    stage: 'verify',
    kind: 'session_started',
    sessionId: 'sr1-routing',
    title: 'routing 判定会话 · 分叉点 #1',
    detail: '判定',
  },
  {
    tsMin: 29.95,
    stage: 'verify',
    kind: 'session_message',
    sessionId: 'sr1-routing',
    title: '思考',
    message: {
      part: 'thinking',
      content:
        'v1 精度 3.1e-2 远超阈值 1e-3，但归因明确：fp16 累加器在 BN scale 求和时精度溢出（analyze_accuracy 已定位到 Compute 内），属代码层缺陷，且经验库 #exp-0117 有成熟修法（中间态升 fp32）。融合路线本身没有精度天花板信号——判：回 implement 修复，不换路线。',
    },
  },
  {
    tsMin: 30.1,
    stage: 'verify',
    kind: 'tool_completed',
    sessionId: 'sr1-routing',
    title: 'route → implement',
    severity: 'success',
    tool: {
      name: 'route',
      input: { next: 'implement' },
      output: {
        next: 'implement',
        reason: '精度超差根因为代码层（fp16 累积误差），修复路径明确且有先例',
        evidence: { max_rel_err: '3.1e-2', threshold: '1e-3', err_best: '首败无历史', 分类: '代码层' },
        confidence: 'high',
      },
    },
  },
  {
    tsMin: 30.25,
    stage: 'verify',
    kind: 'session_ended',
    sessionId: 'sr1-routing',
    title: '判定完成',
  },
  {
    tsMin: 30.35,
    stage: 'verify',
    kind: 'decision',
    title: 'routing 判定 #1 → 回 implement 修复（fp16 累积误差，代码层）',
    severity: 'warning',
    detail: 'route(next=implement, confidence=high)；failures 明细 + #exp-0117 修法注入下一 implement 会话',
  },
  {
    tsMin: 30.38,
    stage: 'verify',
    kind: 'session_started',
    sessionId: 's5-iter-v2',
    title: 'implement 会话 · v2 修复（判定回流）',
    detail: '编码',
  },
  {
    tsMin: 30.4,
    stage: 'verify',
    kind: 'tool_completed',
    sessionId: 's5-iter-v2',
    title: '修复：累加器与中间态升 fp32',
    tool: { name: 'patch_code', input: { file: 'conv_bn_relu_v1.cpp', lines_changed: 6 } },
    artifact: {
      tab: 'diff',
      title: '精度修复：中间态 fp32',
      data: {
        file: 'operator/conv_bn_relu_v1.cpp',
        summary: '累加器与 BN 缩放中间态由 fp16 升为 fp32，出口再转 fp16',
        diff: [
          '@@ operator/conv_bn_relu_v1.cpp @@',
          '  __aicore__ inline void Compute() {',
          '-   LocalTensor<half> acc = calcBuf_.Get<half>();',
          '+   LocalTensor<float> acc = calcBuf_.Get<float>();',
          '    Mmad(acc, xTile, wTile, m, n, k);',
          '-   Mul(bnBuf, acc, gamma, n);',
          '+   Mul(bnBuf, acc, gammaFp32, n);   // fp32 中间态',
          '+   Cast(yTile, bnBuf, RoundMode::CAST_NONE, n);  // 出口降 fp16',
        ].join('\n'),
      },
    },
  },
  { tsMin: 32, stage: 'verify', kind: 'iteration_started', title: '迭代 v2：精度复测', iteration: 'v2' },
  {
    tsMin: 32.3,
    stage: 'verify',
    kind: 'tool_completed',
    sessionId: 's5-iter-v2',
    title: 'v2 编译通过',
    tool: { name: 'build', output: { binary: 'conv_bn_relu_v2.o' }, durationMs: 35_000 },
  },
  {
    tsMin: 34,
    stage: 'verify',
    kind: 'tool_failed',
    sessionId: 's5-iter-v2',
    title: 'v2 精度仍超差',
    severity: 'warning',
    detail: 'max_rel_err 1.8e-3，阈值 1e-3，失败 2 / 80 例（边界用例）',
    tool: {
      name: 'run_test',
      output: { max_rel_err: 1.8e-3, threshold: 1e-3, fail_cases: '2/80（均为 boundary）' },
      durationMs: 58_000,
    },
  },
  {
    tsMin: 34.7,
    stage: 'verify',
    kind: 'tool_completed',
    sessionId: 's5-iter-v2',
    title: '边界用例归因',
    tool: {
      name: 'analyze_accuracy',
      output: {
        root_cause: 'padding 边界读取越界，引入相邻 tile 脏数据',
        fix: '边界掩码读取（BoundaryMode::PAD_ZERO）',
      },
    },
  },
  {
    tsMin: 34.75,
    stage: 'verify',
    kind: 'session_ended',
    sessionId: 's5-iter-v2',
    title: 'v2 修复迭代收尾：误差收敛中，进入分叉点',
  },
  {
    tsMin: 34.8,
    stage: 'verify',
    kind: 'session_started',
    sessionId: 'sr2-routing',
    title: 'routing 判定会话 · 分叉点 #2',
    detail: '判定',
  },
  {
    tsMin: 34.95,
    stage: 'verify',
    kind: 'session_message',
    sessionId: 'sr2-routing',
    title: '思考',
    message: {
      part: 'thinking',
      content:
        '趋势：3.1e-2 → 1.8e-3，一个数量级的收敛；残余 2/80 失败全部是 boundary 用例、归因到 padding 越界读——误差在收敛、根因仍是代码层。err_best 已刷新，没有停滞信号。判：继续 implement 修复。',
    },
  },
  {
    tsMin: 35.1,
    stage: 'verify',
    kind: 'tool_completed',
    sessionId: 'sr2-routing',
    title: 'route → implement',
    severity: 'success',
    tool: {
      name: 'route',
      input: { next: 'implement' },
      output: {
        next: 'implement',
        reason: '误差逐迭代收敛（3.1e-2 → 1.8e-3），残余为边界用例代码层缺陷',
        evidence: { err_trend: ['3.1e-2', '1.8e-3'], err_best: '1.8e-3', 停滞: false, 分类: '代码层' },
        confidence: 'high',
      },
    },
  },
  {
    tsMin: 35.25,
    stage: 'verify',
    kind: 'session_ended',
    sessionId: 'sr2-routing',
    title: '判定完成',
  },
  {
    tsMin: 35.35,
    stage: 'verify',
    kind: 'decision',
    title: 'routing 判定 #2 → 回 implement 修复（误差收敛中，不换路线）',
    severity: 'info',
    detail: 'route(next=implement, confidence=high)；err_best=1.8e-3 仍高于阈值，趋势正常',
  },
  {
    tsMin: 35.45,
    stage: 'verify',
    kind: 'session_started',
    sessionId: 's6-iter-v3',
    title: 'implement 会话 · v3 修复（判定回流）',
    detail: '编码',
  },
  {
    tsMin: 35.5,
    stage: 'verify',
    kind: 'tool_completed',
    sessionId: 's6-iter-v3',
    title: '修复：边界掩码读取',
    tool: { name: 'patch_code', input: { file: 'conv_bn_relu_v1.cpp', lines_changed: 4 } },
    artifact: {
      tab: 'diff',
      title: '精度修复：边界掩码',
      data: {
        file: 'operator/conv_bn_relu_v1.cpp',
        summary: '边界读取改为零填充掩码，杜绝越界脏数据',
        diff: [
          '@@ operator/conv_bn_relu_v1.cpp @@',
          '  // 加载输入 tile',
          '- DataCopy(xTile, xGm[offset], tileLen);',
          '+ DataCopyPad(xTile, xGm[offset], tileLen, BoundaryMode::PAD_ZERO);',
          '+ // PAD_ZERO：越界部分补零，掩码写入合法范围',
        ].join('\n'),
      },
    },
  },
  { tsMin: 37, stage: 'verify', kind: 'iteration_started', title: '迭代 v3：精度复测', iteration: 'v3' },
  {
    tsMin: 37.3,
    stage: 'verify',
    kind: 'tool_completed',
    sessionId: 's6-iter-v3',
    title: 'v3 编译通过',
    tool: { name: 'build', output: { binary: 'conv_bn_relu_v3.o' }, durationMs: 33_000 },
  },
  {
    tsMin: 39.2,
    stage: 'verify',
    kind: 'tool_completed',
    sessionId: 's6-iter-v3',
    title: 'v3 精度通过',
    severity: 'success',
    detail: 'max_rel_err 2.4e-6 ≪ 1e-3，80 / 80 用例通过',
    tool: {
      name: 'run_test',
      output: {
        max_rel_err: 2.4e-6,
        threshold: 1e-3,
        pass: '80/80',
        cosine_similarity: 0.999999,
      },
      durationMs: 61_000,
    },
    artifact: {
      tab: 'accuracy',
      title: '精度报告 · v3',
      data: {
        用例: 'random ×64 + boundary ×16',
        基线: 'CANN 官方实现（关闭 ATC 自动融合）',
        max_rel_err: '2.4e-6',
        阈值: '1e-3',
        通过: '80 / 80',
        cosine_similarity: 0.999999,
        迭代记录: [
          { 版本: 'v1', max_rel_err: '3.1e-2', 结论: '未通过（fp16 累积误差）' },
          { 版本: 'v2', max_rel_err: '1.8e-3', 结论: '未通过（边界越界）' },
          { 版本: 'v3', max_rel_err: '2.4e-6', 结论: '通过' },
        ],
      },
    },
  },
  {
    tsMin: 40.5,
    stage: 'verify',
    kind: 'checkpoint',
    title: '检查点：v3 通过精度门槛',
  },
  {
    tsMin: 40.7,
    stage: 'verify',
    kind: 'session_ended',
    sessionId: 's6-iter-v3',
    title: 'v3 达标（80/80，2.4e-6）',
  },
  {
    tsMin: 41,
    stage: 'verify',
    kind: 'stage_completed',
    title: '测试完成：3 次迭代，v3 通过',
    severity: 'success',
  },

  // ── 阶段 5：基准 ────────────────────────────────────────────
  { tsMin: 41.1, stage: 'bench', kind: 'stage_started', title: '开始性能基准' },
  {
    tsMin: 41.15,
    stage: 'bench',
    kind: 'session_started',
    sessionId: 's7-bench',
    title: 'bench 会话 · 双份测量',
    detail: '基准',
  },
  {
    tsMin: 41.2,
    stage: 'bench',
    kind: 'session_message',
    sessionId: 's7-bench',
    title: '思考',
    message: {
      part: 'thinking',
      content:
        '口径先钉死：基线走官方单算子 API（关闭 ATC 自动融合），预热 20 / 迭代 100，判死只看 p50，同步点 aclrtSynchronizeStream。双份测量先基线后优化，同卡同频。',
    },
  },
  {
    tsMin: 41.4,
    stage: 'bench',
    kind: 'tool_completed',
    sessionId: 's7-bench',
    title: '基准环境确认',
    detail: '官方基线以单算子 API 调用运行（关闭 ATC 自动融合），预热 20 次 / 迭代 100 次',
    tool: {
      name: 'bench_setup',
      input: {
        device: 'Ascend 910B',
        baseline: 'CANN 官方实现（--disable_fusion）',
        warmup: 20,
        iters: 100,
        metric: 'p50 / p99 时延',
      },
      output: { ready: true },
    },
  },
  {
    tsMin: 43,
    stage: 'bench',
    kind: 'tool_completed',
    sessionId: 's7-bench',
    title: '官方基线测量完成',
    tool: {
      name: 'run_bench',
      output: { target: 'baseline', p50: 1.08, p99: 1.35, unit: 'ms' },
      durationMs: 92_000,
    },
  },
  {
    tsMin: 45,
    stage: 'bench',
    kind: 'tool_completed',
    sessionId: 's7-bench',
    title: '融合算子 v3 测量完成：+6.2%',
    severity: 'success',
    tool: {
      name: 'run_bench',
      output: { target: 'optimized', p50: 1.013, p99: 1.21, unit: 'ms' },
      durationMs: 95_000,
    },
    artifact: {
      tab: 'bench',
      title: '性能对比：融合算子 v3 vs 官方基线',
      data: {
        baselineName: '官方实现（关闭 ATC 融合）',
        optimizedName: '融合算子 v3',
        unit: 'ms',
        baseline: { p50: 1.08, p99: 1.35 },
        optimized: { p50: 1.013, p99: 1.21 },
        gainPct: 6.2,
        note: '预热 20 次 / 迭代 100 次，取 p50 / p99',
      },
    },
  },
  {
    tsMin: 46.5,
    stage: 'bench',
    kind: 'decision',
    title: '达标：+6.2% ≥ 目标 +5%，进入交付流程',
    severity: 'success',
  },
  {
    tsMin: 47.8,
    stage: 'bench',
    kind: 'session_ended',
    sessionId: 's7-bench',
    title: 'bench 完成（+6.2% 达标）',
  },
  {
    tsMin: 48,
    stage: 'bench',
    kind: 'stage_completed',
    title: '基准完成：+6.2% vs 官方',
    severity: 'success',
  },

  // ── 阶段 6：总结 ────────────────────────────────────────────
  { tsMin: 48.1, stage: 'summarize', kind: 'stage_started', title: '开始经验总结' },
  {
    tsMin: 48.15,
    stage: 'summarize',
    kind: 'session_started',
    sessionId: 's8-summarize',
    title: 'summarize 会话 · 经验回流',
    detail: '总结',
  },
  {
    tsMin: 48.25,
    stage: 'summarize',
    kind: 'session_message',
    sessionId: 's8-summarize',
    title: '思考',
    message: {
      part: 'thinking',
      content:
        '这次 run 值得沉淀的是精度修复链：fp16 累积 → 升 fp32 中间态 → 边界越界 → PAD_ZERO 掩码。复用条件写宽一点：凡是"逐元素融合 + 累加/reduce 语义 + 存在 padding"都该先排查这两类。',
    },
  },
  {
    tsMin: 48.4,
    stage: 'summarize',
    kind: 'tool_completed',
    sessionId: 's8-summarize',
    title: '经验条目写入知识库',
    detail: '经验编号 #exp-0132，后续任务可经 RAG 检索复用',
    tool: { name: 'experience_write', output: { id: 'exp-0132', status: 'written' } },
    artifact: {
      tab: 'experience',
      title: '经验回流条目 · #exp-0132',
      data: {
        问题: 'Conv2D+BN+ReLU 融合算子精度超差（3.1e-2）',
        症状: 'random 用例大面积超差，max_rel_err 远大于 1e-3',
        根因: ['fp16 累加器在 BN scale 求和时精度溢出', 'padding 边界读取越界引入脏数据'],
        方案: ['累加器与中间态升 fp32，出口再 Cast 回 fp16', '边界 DataCopyPad 零填充掩码'],
        复用条件: '逐元素融合含累加 / reduce 语义，或输入存在非对齐 padding 时优先排查',
        结果: '修复后 80/80 通过，性能 +6.2% vs 官方实现',
      },
    },
  },
  {
    tsMin: 49.3,
    stage: 'summarize',
    kind: 'session_ended',
    sessionId: 's8-summarize',
    title: 'summarize 完成',
  },
  {
    tsMin: 49.5,
    stage: 'summarize',
    kind: 'stage_completed',
    title: '总结完成',
    severity: 'success',
  },

  // ── 阶段 7：交付 ────────────────────────────────────────────
  { tsMin: 49.6, stage: 'deliver', kind: 'stage_started', title: '开始交付打包' },
  {
    tsMin: 49.7,
    stage: 'deliver',
    kind: 'session_started',
    sessionId: 's9-deliver',
    title: 'deliver 会话 · 打包与报告',
    detail: '交付',
  },
  {
    tsMin: 50,
    stage: 'deliver',
    kind: 'tool_completed',
    sessionId: 's9-deliver',
    title: '交付包打包完成',
    tool: { name: 'package', output: { files: 17, size: '312 KB' } },
    artifact: {
      tab: 'meta',
      title: '交付清单',
      data: {
        'code/': 'conv_bn_relu_v3 算子源码 + host 侧调用 + CMake 脚本',
        'tests/': '80 个精度用例 + 基准脚本（关闭 ATC 融合）',
        'STRATEGY.md': '优化策略文档（方案#2）',
        'REPORT.md': '精度 + 性能报告',
        'experience/exp-0132.json': '经验回流条目',
        复现: 'bash run.sh && bash bench.sh',
      },
    },
  },
  {
    tsMin: 50.6,
    stage: 'deliver',
    kind: 'tool_completed',
    sessionId: 's9-deliver',
    title: '生成交付报告',
    tool: { name: 'gen_report', output: { file: 'REPORT.md' } },
    artifact: {
      tab: 'report',
      title: '交付报告 · REPORT.md',
      data: {
        content: [
          '# resnet50 · Conv2D+BN+ReLU 融合优化报告',
          '',
          '## 任务',
          '- 输入：resnet50_bs16.onnx（42 算子 / 6 类融合机会）',
          '- 优化对象：16 处 Conv2D+BN+ReLU 热点段，方案#2（BN 折叠 + ReLU epilogue）',
          '',
          '## 精度',
          '- 基线：CANN 官方实现，单算子 API 逐个调用，关闭 ATC 自动融合',
          '- v3：80 / 80 用例通过，max_rel_err 2.4e-6（阈值 1e-3）',
          '- 迭代：v1 3.1e-2 → v2 1.8e-3 → v3 2.4e-6',
          '',
          '## 性能',
          '- 官方基线：p50 1.08 ms / p99 1.35 ms',
          '- 融合算子 v3：p50 1.013 ms / p99 1.21 ms',
          '- 提升：+6.2%（目标 +5%，达标）',
          '',
          '## 结论',
          '- 交付包就绪，经验 #exp-0132 已回流知识库',
        ].join('\n'),
      },
    },
  },
  {
    tsMin: 50.9,
    stage: 'deliver',
    kind: 'session_ended',
    sessionId: 's9-deliver',
    title: 'deliver 完成',
  },
  {
    tsMin: 51,
    stage: 'deliver',
    kind: 'stage_completed',
    title: '交付完成：完整交付包就绪',
    severity: 'success',
  },
  {
    tsMin: 51.2,
    stage: 'deliver',
    kind: 'note',
    title: 'Run 完成：+6.2% vs 官方基线',
    severity: 'success',
  },
];

export const resnet50Scenario: Scenario = buildScenario(
  {
    id: 'run-resnet50',
    templateName: '整网模型 · resnet50',
    templateDesc: 'Conv2D+BN+ReLU 融合全流程（含 3 轮迭代修复、+6.2% 达标交付）',
    meta: {
      id: 'run-resnet50',
      name: 'resnet50 算子融合优化',
      taskType: 'model',
      model: 'resnet50 (bs16 · 224×224)',
      targetGainPct: 5,
      startTimeLabel: '14:02',
    },
  },
  raw,
  51.4 * 60_000,
);
