import { buildScenario, type RawEvent, type Scenario } from '../types';

const raw: RawEvent[] = [
  { tsMin: 0, stage: 'identify', kind: 'stage_started', title: '开始算子识别' },
  {
    tsMin: 0.4,
    stage: 'identify',
    kind: 'tool_completed',
    title: '解析模型文件',
    tool: {
      name: 'parse_model',
      input: { file: 'swinv2_base_bs8.onnx', format: 'ONNX' },
      output: { ops: 58, graph_nodes: 241, input_shape: 'NCHW 8×3×256×256' },
    },
  },
  {
    tsMin: 2,
    stage: 'identify',
    kind: 'tool_completed',
    title: '扫描融合机会',
    tool: {
      name: 'fusion_scan',
      output: {
        candidates: 4,
        top: [
          { pattern: 'SW-MHA 窗口注意力融合', count: 12, est_gain: '+5~7%' },
          { pattern: 'Conv1x1 纵向融合', count: 24, est_gain: '+3%' },
        ],
      },
    },
  },
  {
    tsMin: 4,
    stage: 'identify',
    kind: 'stage_completed',
    title: '识别完成：58 个算子 / 4 类融合机会',
    severity: 'success',
  },

  { tsMin: 4.1, stage: 'strategy', kind: 'stage_started', title: '开始策略生成' },
  {
    tsMin: 4.6,
    stage: 'strategy',
    kind: 'tool_completed',
    title: 'RAG 检索注意力融合先例',
    tool: {
      name: 'retrieve',
      input: { query: 'window attention QKV 融合 softmax', top_k: 3 },
      output: {
        hits: [
          { source: 'CANN 文档', title: 'Matmul 分块与 Softmax 向量段', score: 0.89 },
          { source: '经验库 #exp-0102', title: '相对位置偏置预展开', score: 0.84 },
        ],
      },
    },
  },
  {
    tsMin: 7,
    stage: 'strategy',
    kind: 'tool_completed',
    title: '生成融合方案 #1',
    tool: {
      name: 'strategy_gen',
      input: { pattern: 'SW-MHA 窗口注意力', impl: 'AscendC 混合算子' },
      output: { plan: '方案#1', est_gain: '+6%', risk: 'mask 索引映射需验证' },
      durationMs: 128_000,
    },
    artifact: {
      tab: 'strategy',
      title: '优化策略文档 · 方案#1',
      data: {
        content: [
          '# SW-MHA 窗口注意力融合优化策略（方案#1）',
          '',
          '## 目标',
          '- 输入模型：swinv2_base（bs8，256×256，window 8×8）',
          '- 优化对象：12 处 SW-MHA 窗口注意力段，目标 +5%',
          '',
          '## 融合方案',
          '- QKV 三投影合入单个 GEMM（3N 出口），减少两次 kernel 发射',
          '- 窗口重排（im2win）在 GM 侧一次完成，Q·K 与 softmax·V 以 tile 流水衔接',
          '- 相对位置偏置表预展开随 TilingData 下发，避免每 tile 重复计算',
          '',
          '## 风险与对策',
          '- mask 到窗口的索引映射：边界窗口与 padding 窗口分别建表',
        ].join('\n'),
      },
    },
  },
  {
    tsMin: 10,
    stage: 'strategy',
    kind: 'stage_completed',
    title: '策略完成：方案#1 · 预期 +6%',
    severity: 'success',
  },

  { tsMin: 10.1, stage: 'implement', kind: 'stage_started', title: '开始代码编写' },
  {
    tsMin: 10.5,
    stage: 'implement',
    kind: 'tool_completed',
    title: '生成融合算子 v1 代码',
    tool: {
      name: 'code_gen',
      input: { file: 'operator/sw_mha_v1.cpp', lines: 336 },
      output: { status: 'generated' },
      durationMs: 260_000,
    },
    artifact: {
      tab: 'diff',
      title: '窗口注意力融合算子 v1 生成',
      data: {
        file: 'operator/sw_mha_v1.cpp（新增 336 行）',
        summary: 'QKV 合并 GEMM + im2win 重排 + softmax·V 流水',
        diff: [
          '@@ operator/sw_mha_v1.cpp @@',
          '+ // QKV 合并投影：单 GEMM 一次产出 Q/K/V 三段',
          '+ Mmad(qkvTile, xTile, wqkvTile, m, 3n, k);',
          '+',
          '+ // im2win：窗口重排索引表由 host 预生成',
          '+ DataCopy(winIdx, winIdxGm, winTableLen);',
        ].join('\n'),
      },
    },
  },
  {
    tsMin: 13,
    stage: 'implement',
    kind: 'tool_completed',
    title: 'v1 编译通过',
    severity: 'success',
    tool: { name: 'build', output: { binary: 'sw_mha_v1.o' }, durationMs: 55_000 },
  },
  {
    tsMin: 14,
    stage: 'implement',
    kind: 'stage_completed',
    title: '编码完成：v1 编译通过',
    severity: 'success',
  },

  { tsMin: 14.1, stage: 'verify', kind: 'stage_started', title: '开始测试回归' },
  { tsMin: 14.3, stage: 'verify', kind: 'iteration_started', title: '迭代 v1：精度验证', iteration: 'v1' },
  {
    tsMin: 14.5,
    stage: 'verify',
    kind: 'tool_completed',
    title: '生成测试用例',
    detail: '基线：官方实现逐算子调用（aclnn 单算子，无 ATC 图融合）',
    tool: { name: 'gen_test', input: { cases: 'random ×48 + window 边界 ×12' }, output: { cases: 60 } },
  },
  {
    tsMin: 17,
    stage: 'verify',
    kind: 'tool_failed',
    title: 'v1 精度超差',
    severity: 'error',
    detail: '失败 6 / 60 例，均为窗口边界用例',
    tool: {
      name: 'run_test',
      output: { max_rel_err: 2.0e-2, threshold: 1e-3, fail_cases: '6/60（window 边界）' },
    },
  },
  {
    tsMin: 17.6,
    stage: 'verify',
    kind: 'tool_completed',
    title: '边界用例归因',
    tool: {
      name: 'analyze_accuracy',
      output: { root_cause: 'mask 到窗口索引错位：右/下边界窗口复用了内窗索引表', fix: '按窗口类别分表索引' },
    },
  },
  {
    tsMin: 18.4,
    stage: 'verify',
    kind: 'tool_completed',
    title: '修复：mask 索引分表',
    tool: { name: 'patch_code', input: { file: 'sw_mha_v1.cpp', lines_changed: 9 } },
    artifact: {
      tab: 'diff',
      title: '精度修复：mask 索引分表',
      data: {
        file: 'operator/sw_mha_v1.cpp',
        summary: '边界窗口（右/下/右下）与内窗分别使用独立索引表',
        diff: [
          '@@ operator/sw_mha_v1.cpp @@',
          '- const auto& idx = winIdxTable[winId];',
          '+ const auto& idx = winId < innerWinCount',
          '+     ? innerIdxTable[winId]          // 内窗',
          '+     : boundaryIdxTable[winId - innerWinCount];  // 边界窗',
        ].join('\n'),
      },
    },
  },
  { tsMin: 21, stage: 'verify', kind: 'iteration_started', title: '迭代 v2：精度复测', iteration: 'v2' },
  {
    tsMin: 21.3,
    stage: 'verify',
    kind: 'tool_completed',
    title: 'v2 编译通过',
    tool: { name: 'build', output: { binary: 'sw_mha_v2.o' }, durationMs: 52_000 },
  },
  {
    tsMin: 23.5,
    stage: 'verify',
    kind: 'tool_completed',
    title: 'v2 精度通过',
    severity: 'success',
    detail: 'max_rel_err 8e-7，60 / 60 用例通过',
    tool: { name: 'run_test', output: { max_rel_err: 8e-7, pass: '60/60' } },
    artifact: {
      tab: 'accuracy',
      title: '精度报告 · v2',
      data: {
        用例: 'random ×48 + window 边界 ×12',
        基线: 'CANN 官方实现（aclnn 单算子 + ATC 门槛）',
        max_rel_err: '8e-7',
        通过: '60 / 60',
        迭代记录: [
          { 版本: 'v1', max_rel_err: '2.0e-2', 结论: '未通过（窗口边界索引错位）' },
          { 版本: 'v2', max_rel_err: '8e-7', 结论: '通过' },
        ],
      },
    },
  },
  {
    tsMin: 25,
    stage: 'verify',
    kind: 'stage_completed',
    title: '测试完成：2 次迭代，v2 通过',
    severity: 'success',
  },

  { tsMin: 25.1, stage: 'bench', kind: 'stage_started', title: '开始性能基准' },
  {
    tsMin: 25.4,
    stage: 'bench',
    kind: 'tool_completed',
    title: '基准环境确认',
    detail: '官方基线走 aclnn 单算子 API（无 ATC 图融合），预热 20 / 迭代 100；另测 ATC 门槛对照',
    tool: { name: 'bench_setup', input: { baseline: 'CANN 官方实现（aclnn 单算子）+ ATC 门槛对照' }, output: { ready: true } },
  },
  {
    tsMin: 27.5,
    stage: 'bench',
    kind: 'tool_completed',
    title: '官方基线测量完成',
    tool: { name: 'run_bench', output: { target: 'baseline', p50: 0.97, p99: 1.18, unit: 'ms' } },
  },
  {
    tsMin: 29.5,
    stage: 'bench',
    kind: 'tool_completed',
    title: '融合算子 v2 测量完成：+5.1%',
    severity: 'success',
    tool: { name: 'run_bench', output: { target: 'optimized', p50: 0.9205, p99: 1.09, unit: 'ms' } },
    artifact: {
      tab: 'bench',
      title: '性能对比：窗口注意力融合 v2 vs 官方基线',
      data: {
        baselineName: '官方实现（aclnn 单算子）',
        optimizedName: 'SW-MHA 融合 v2',
        unit: 'ms',
        baseline: { p50: 0.97, p99: 1.18 },
        optimized: { p50: 0.9205, p99: 1.09 },
        gainPct: 5.1,
        note: '预热 20 次 / 迭代 100 次，取 p50 / p99',
      },
    },
  },
  {
    tsMin: 31,
    stage: 'bench',
    kind: 'stage_completed',
    title: '基准完成：+5.1% vs 官方',
    severity: 'success',
  },

  { tsMin: 31.1, stage: 'summarize', kind: 'stage_started', title: '开始经验总结' },
  {
    tsMin: 31.5,
    stage: 'summarize',
    kind: 'tool_completed',
    title: '经验条目写入知识库',
    detail: '经验编号 #exp-0133',
    tool: { name: 'experience_write', output: { id: 'exp-0133', status: 'written' } },
    artifact: {
      tab: 'experience',
      title: '经验回流条目 · #exp-0133',
      data: {
        问题: 'SW-MHA 窗口注意力融合后边界用例精度超差',
        根因: '右/下边界窗口复用内窗 mask 索引表，导致注意力权重错位',
        方案: '窗口按内窗 / 边界窗分类建表索引，host 侧随 TilingData 下发',
        复用条件: '任何涉及窗口 / 分块重排的融合，边界块必须独立索引',
        结果: '60/60 通过，性能 +5.1% vs 官方实现',
      },
    },
  },
  {
    tsMin: 32.5,
    stage: 'summarize',
    kind: 'stage_completed',
    title: '总结完成',
    severity: 'success',
  },

  { tsMin: 32.6, stage: 'deliver', kind: 'stage_started', title: '开始交付打包' },
  {
    tsMin: 33,
    stage: 'deliver',
    kind: 'tool_completed',
    title: '交付包打包完成',
    tool: { name: 'package', output: { files: 21, size: '405 KB' } },
    artifact: {
      tab: 'meta',
      title: '交付清单',
      data: {
        'code/': 'sw_mha_v2 算子源码 + host 侧调用 + CMake 脚本',
        'tests/': '60 个精度用例 + 基准脚本（aclnn 基线 + ATC 门槛）',
        'STRATEGY.md': '优化策略文档（方案#1）',
        'REPORT.md': '精度 + 性能报告',
        'experience/exp-0133.json': '经验回流条目',
      },
    },
  },
  {
    tsMin: 33.6,
    stage: 'deliver',
    kind: 'tool_completed',
    title: '生成交付报告',
    tool: { name: 'gen_report', output: { file: 'REPORT.md' } },
    artifact: {
      tab: 'report',
      title: '交付报告 · REPORT.md',
      data: {
        content: [
          '# swinv2_base · SW-MHA 窗口注意力融合优化报告',
          '',
          '## 任务',
          '- 输入：swinv2_base_bs8.onnx（58 算子 / 4 类融合机会）',
          '- 优化对象：12 处 SW-MHA 窗口注意力段，方案#1',
          '',
          '## 精度',
          '- v2：60 / 60 通过，max_rel_err 8e-7（阈值 1e-3）',
          '',
          '## 性能',
          '- 官方基线：p50 0.97 ms / p99 1.18 ms',
          '- 融合算子 v2：p50 0.921 ms / p99 1.09 ms',
          '- 提升：+5.1%（目标 +5%，达标）',
        ].join('\n'),
      },
    },
  },
  {
    tsMin: 34,
    stage: 'deliver',
    kind: 'stage_completed',
    title: '交付完成：完整交付包就绪',
    severity: 'success',
  },
  {
    tsMin: 34.2,
    stage: 'deliver',
    kind: 'note', 
    title: 'Run 完成：+5.1% vs 官方基线',
    severity: 'success',
  },
];

export const swinv2Scenario: Scenario = buildScenario(
  {
    id: 'run-swinv2',
    templateName: '整网模型 · swinv2',
    templateDesc: 'SW-MHA 窗口注意力融合（2 轮迭代，+5.1% 达标交付）',
    meta: {
      id: 'run-swinv2',
      name: 'swinv2 窗口注意力融合',
      taskType: 'model',
      model: 'swinv2_base (bs8 · 256×256)',
      targetGainPct: 5,
      startTimeLabel: '09:40',
    },
  },
  raw,
  34.4 * 60_000,
);
